name: Checks for @repo/utils
description: Run static checks and tests.
runs:
  using: composite
  steps:
    - name: Static checks
      shell: bash
      working-directory: packages/utils
      run: pnpm exec vp check --no-error-on-unmatched-pattern .
    - name: Test
      if: ${{ !cancelled() }}
      shell: bash
      working-directory: packages/utils
      run: pnpm exec vp test run
