/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as SignupIndexRouteImport } from "./routes/signup/index"
import { Route as LoginIndexRouteImport } from "./routes/login/index"
import { Route as AuthenticatedShellRouteRouteImport } from "./routes/_authenticated/_shell/route"
import { Route as AuthenticatedOnboardingIndexRouteImport } from "./routes/_authenticated/onboarding/index"
import { Route as AuthenticatedNewOrgIndexRouteImport } from "./routes/_authenticated/new-org/index"
import { Route as AuthenticatedShellSuperadminRouteRouteImport } from "./routes/_authenticated/_shell/superadmin/route"
import { Route as AuthenticatedShellDashboardRouteRouteImport } from "./routes/_authenticated/_shell/_dashboard/route"
import { Route as AuthenticatedShellSuperadminIndexRouteImport } from "./routes/_authenticated/_shell/superadmin/index"
import { Route as AuthenticatedShellAccountIndexRouteImport } from "./routes/_authenticated/_shell/account/index"
import { Route as AuthenticatedShellDashboardIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/index"
import { Route as AuthenticatedShellSuperadminOrganizationsRouteImport } from "./routes/_authenticated/_shell/superadmin/organizations"
import { Route as AuthenticatedShellDashboardSettingsRouteRouteImport } from "./routes/_authenticated/_shell/_dashboard/settings/route"
import { Route as AuthenticatedShellDashboardTimeIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/time/index"
import { Route as AuthenticatedShellDashboardSettingsIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/settings/index"
import { Route as AuthenticatedShellDashboardProjectsIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/projects/index"
import { Route as AuthenticatedShellDashboardInvoicesIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/invoices/index"
import { Route as AuthenticatedShellDashboardClientsIndexRouteImport } from "./routes/_authenticated/_shell/_dashboard/clients/index"
import { Route as AuthenticatedShellDashboardSettingsMembersRouteImport } from "./routes/_authenticated/_shell/_dashboard/settings/members"
import { Route as AuthenticatedShellDashboardSettingsGeneralRouteImport } from "./routes/_authenticated/_shell/_dashboard/settings/general"
import { Route as AuthenticatedShellDashboardSettingsApiKeysRouteImport } from "./routes/_authenticated/_shell/_dashboard/settings/api-keys"
import { Route as AuthenticatedShellDashboardProjectsProjectSlugRouteImport } from "./routes/_authenticated/_shell/_dashboard/projects/$projectSlug"
import { Route as AuthenticatedShellDashboardInvoicesNewRouteImport } from "./routes/_authenticated/_shell/_dashboard/invoices/new"
import { Route as AuthenticatedShellDashboardInvoicesInvoiceIdRouteImport } from "./routes/_authenticated/_shell/_dashboard/invoices/$invoiceId"
import { Route as AuthenticatedShellDashboardClientsClientIdRouteImport } from "./routes/_authenticated/_shell/_dashboard/clients/$clientId"
import { Route as AuthenticatedShellDashboardInvoicesInvoiceIdPrintRouteImport } from "./routes/_authenticated/_shell/_dashboard/invoices/$invoiceId.print"

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: "/signup/",
  path: "/signup/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRouteRoute = AuthenticatedShellRouteRouteImport.update({
  id: "/_shell",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: "/onboarding/",
    path: "/onboarding/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewOrgIndexRoute =
  AuthenticatedNewOrgIndexRouteImport.update({
    id: "/new-org/",
    path: "/new-org/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShellSuperadminRouteRoute =
  AuthenticatedShellSuperadminRouteRouteImport.update({
    id: "/superadmin",
    path: "/superadmin",
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellDashboardRouteRoute =
  AuthenticatedShellDashboardRouteRouteImport.update({
    id: "/_dashboard",
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSuperadminIndexRoute =
  AuthenticatedShellSuperadminIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedShellSuperadminRouteRoute,
  } as any)
const AuthenticatedShellAccountIndexRoute =
  AuthenticatedShellAccountIndexRouteImport.update({
    id: "/account/",
    path: "/account/",
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellDashboardIndexRoute =
  AuthenticatedShellDashboardIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellSuperadminOrganizationsRoute =
  AuthenticatedShellSuperadminOrganizationsRouteImport.update({
    id: "/organizations",
    path: "/organizations",
    getParentRoute: () => AuthenticatedShellSuperadminRouteRoute,
  } as any)
const AuthenticatedShellDashboardSettingsRouteRoute =
  AuthenticatedShellDashboardSettingsRouteRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardTimeIndexRoute =
  AuthenticatedShellDashboardTimeIndexRouteImport.update({
    id: "/time/",
    path: "/time/",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardSettingsIndexRoute =
  AuthenticatedShellDashboardSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedShellDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedShellDashboardProjectsIndexRoute =
  AuthenticatedShellDashboardProjectsIndexRouteImport.update({
    id: "/projects/",
    path: "/projects/",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardInvoicesIndexRoute =
  AuthenticatedShellDashboardInvoicesIndexRouteImport.update({
    id: "/invoices/",
    path: "/invoices/",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardClientsIndexRoute =
  AuthenticatedShellDashboardClientsIndexRouteImport.update({
    id: "/clients/",
    path: "/clients/",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardSettingsMembersRoute =
  AuthenticatedShellDashboardSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => AuthenticatedShellDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedShellDashboardSettingsGeneralRoute =
  AuthenticatedShellDashboardSettingsGeneralRouteImport.update({
    id: "/general",
    path: "/general",
    getParentRoute: () => AuthenticatedShellDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedShellDashboardSettingsApiKeysRoute =
  AuthenticatedShellDashboardSettingsApiKeysRouteImport.update({
    id: "/api-keys",
    path: "/api-keys",
    getParentRoute: () => AuthenticatedShellDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedShellDashboardProjectsProjectSlugRoute =
  AuthenticatedShellDashboardProjectsProjectSlugRouteImport.update({
    id: "/projects/$projectSlug",
    path: "/projects/$projectSlug",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardInvoicesNewRoute =
  AuthenticatedShellDashboardInvoicesNewRouteImport.update({
    id: "/invoices/new",
    path: "/invoices/new",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardInvoicesInvoiceIdRoute =
  AuthenticatedShellDashboardInvoicesInvoiceIdRouteImport.update({
    id: "/invoices/$invoiceId",
    path: "/invoices/$invoiceId",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardClientsClientIdRoute =
  AuthenticatedShellDashboardClientsClientIdRouteImport.update({
    id: "/clients/$clientId",
    path: "/clients/$clientId",
    getParentRoute: () => AuthenticatedShellDashboardRouteRoute,
  } as any)
const AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute =
  AuthenticatedShellDashboardInvoicesInvoiceIdPrintRouteImport.update({
    id: "/print",
    path: "/print",
    getParentRoute: () => AuthenticatedShellDashboardInvoicesInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedShellDashboardIndexRoute
  "/login/": typeof LoginIndexRoute
  "/signup/": typeof SignupIndexRoute
  "/superadmin": typeof AuthenticatedShellSuperadminRouteRouteWithChildren
  "/new-org/": typeof AuthenticatedNewOrgIndexRoute
  "/onboarding/": typeof AuthenticatedOnboardingIndexRoute
  "/settings": typeof AuthenticatedShellDashboardSettingsRouteRouteWithChildren
  "/superadmin/organizations": typeof AuthenticatedShellSuperadminOrganizationsRoute
  "/account/": typeof AuthenticatedShellAccountIndexRoute
  "/superadmin/": typeof AuthenticatedShellSuperadminIndexRoute
  "/clients/$clientId": typeof AuthenticatedShellDashboardClientsClientIdRoute
  "/invoices/$invoiceId": typeof AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren
  "/invoices/new": typeof AuthenticatedShellDashboardInvoicesNewRoute
  "/projects/$projectSlug": typeof AuthenticatedShellDashboardProjectsProjectSlugRoute
  "/settings/api-keys": typeof AuthenticatedShellDashboardSettingsApiKeysRoute
  "/settings/general": typeof AuthenticatedShellDashboardSettingsGeneralRoute
  "/settings/members": typeof AuthenticatedShellDashboardSettingsMembersRoute
  "/clients/": typeof AuthenticatedShellDashboardClientsIndexRoute
  "/invoices/": typeof AuthenticatedShellDashboardInvoicesIndexRoute
  "/projects/": typeof AuthenticatedShellDashboardProjectsIndexRoute
  "/settings/": typeof AuthenticatedShellDashboardSettingsIndexRoute
  "/time/": typeof AuthenticatedShellDashboardTimeIndexRoute
  "/invoices/$invoiceId/print": typeof AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedShellDashboardIndexRoute
  "/login": typeof LoginIndexRoute
  "/signup": typeof SignupIndexRoute
  "/new-org": typeof AuthenticatedNewOrgIndexRoute
  "/onboarding": typeof AuthenticatedOnboardingIndexRoute
  "/superadmin/organizations": typeof AuthenticatedShellSuperadminOrganizationsRoute
  "/account": typeof AuthenticatedShellAccountIndexRoute
  "/superadmin": typeof AuthenticatedShellSuperadminIndexRoute
  "/clients/$clientId": typeof AuthenticatedShellDashboardClientsClientIdRoute
  "/invoices/$invoiceId": typeof AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren
  "/invoices/new": typeof AuthenticatedShellDashboardInvoicesNewRoute
  "/projects/$projectSlug": typeof AuthenticatedShellDashboardProjectsProjectSlugRoute
  "/settings/api-keys": typeof AuthenticatedShellDashboardSettingsApiKeysRoute
  "/settings/general": typeof AuthenticatedShellDashboardSettingsGeneralRoute
  "/settings/members": typeof AuthenticatedShellDashboardSettingsMembersRoute
  "/clients": typeof AuthenticatedShellDashboardClientsIndexRoute
  "/invoices": typeof AuthenticatedShellDashboardInvoicesIndexRoute
  "/projects": typeof AuthenticatedShellDashboardProjectsIndexRoute
  "/settings": typeof AuthenticatedShellDashboardSettingsIndexRoute
  "/time": typeof AuthenticatedShellDashboardTimeIndexRoute
  "/invoices/$invoiceId/print": typeof AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/_authenticated/_shell": typeof AuthenticatedShellRouteRouteWithChildren
  "/login/": typeof LoginIndexRoute
  "/signup/": typeof SignupIndexRoute
  "/_authenticated/_shell/_dashboard": typeof AuthenticatedShellDashboardRouteRouteWithChildren
  "/_authenticated/_shell/superadmin": typeof AuthenticatedShellSuperadminRouteRouteWithChildren
  "/_authenticated/new-org/": typeof AuthenticatedNewOrgIndexRoute
  "/_authenticated/onboarding/": typeof AuthenticatedOnboardingIndexRoute
  "/_authenticated/_shell/_dashboard/settings": typeof AuthenticatedShellDashboardSettingsRouteRouteWithChildren
  "/_authenticated/_shell/superadmin/organizations": typeof AuthenticatedShellSuperadminOrganizationsRoute
  "/_authenticated/_shell/_dashboard/": typeof AuthenticatedShellDashboardIndexRoute
  "/_authenticated/_shell/account/": typeof AuthenticatedShellAccountIndexRoute
  "/_authenticated/_shell/superadmin/": typeof AuthenticatedShellSuperadminIndexRoute
  "/_authenticated/_shell/_dashboard/clients/$clientId": typeof AuthenticatedShellDashboardClientsClientIdRoute
  "/_authenticated/_shell/_dashboard/invoices/$invoiceId": typeof AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren
  "/_authenticated/_shell/_dashboard/invoices/new": typeof AuthenticatedShellDashboardInvoicesNewRoute
  "/_authenticated/_shell/_dashboard/projects/$projectSlug": typeof AuthenticatedShellDashboardProjectsProjectSlugRoute
  "/_authenticated/_shell/_dashboard/settings/api-keys": typeof AuthenticatedShellDashboardSettingsApiKeysRoute
  "/_authenticated/_shell/_dashboard/settings/general": typeof AuthenticatedShellDashboardSettingsGeneralRoute
  "/_authenticated/_shell/_dashboard/settings/members": typeof AuthenticatedShellDashboardSettingsMembersRoute
  "/_authenticated/_shell/_dashboard/clients/": typeof AuthenticatedShellDashboardClientsIndexRoute
  "/_authenticated/_shell/_dashboard/invoices/": typeof AuthenticatedShellDashboardInvoicesIndexRoute
  "/_authenticated/_shell/_dashboard/projects/": typeof AuthenticatedShellDashboardProjectsIndexRoute
  "/_authenticated/_shell/_dashboard/settings/": typeof AuthenticatedShellDashboardSettingsIndexRoute
  "/_authenticated/_shell/_dashboard/time/": typeof AuthenticatedShellDashboardTimeIndexRoute
  "/_authenticated/_shell/_dashboard/invoices/$invoiceId/print": typeof AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login/"
    | "/signup/"
    | "/superadmin"
    | "/new-org/"
    | "/onboarding/"
    | "/settings"
    | "/superadmin/organizations"
    | "/account/"
    | "/superadmin/"
    | "/clients/$clientId"
    | "/invoices/$invoiceId"
    | "/invoices/new"
    | "/projects/$projectSlug"
    | "/settings/api-keys"
    | "/settings/general"
    | "/settings/members"
    | "/clients/"
    | "/invoices/"
    | "/projects/"
    | "/settings/"
    | "/time/"
    | "/invoices/$invoiceId/print"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/new-org"
    | "/onboarding"
    | "/superadmin/organizations"
    | "/account"
    | "/superadmin"
    | "/clients/$clientId"
    | "/invoices/$invoiceId"
    | "/invoices/new"
    | "/projects/$projectSlug"
    | "/settings/api-keys"
    | "/settings/general"
    | "/settings/members"
    | "/clients"
    | "/invoices"
    | "/projects"
    | "/settings"
    | "/time"
    | "/invoices/$invoiceId/print"
  id:
    | "__root__"
    | "/_authenticated"
    | "/_authenticated/_shell"
    | "/login/"
    | "/signup/"
    | "/_authenticated/_shell/_dashboard"
    | "/_authenticated/_shell/superadmin"
    | "/_authenticated/new-org/"
    | "/_authenticated/onboarding/"
    | "/_authenticated/_shell/_dashboard/settings"
    | "/_authenticated/_shell/superadmin/organizations"
    | "/_authenticated/_shell/_dashboard/"
    | "/_authenticated/_shell/account/"
    | "/_authenticated/_shell/superadmin/"
    | "/_authenticated/_shell/_dashboard/clients/$clientId"
    | "/_authenticated/_shell/_dashboard/invoices/$invoiceId"
    | "/_authenticated/_shell/_dashboard/invoices/new"
    | "/_authenticated/_shell/_dashboard/projects/$projectSlug"
    | "/_authenticated/_shell/_dashboard/settings/api-keys"
    | "/_authenticated/_shell/_dashboard/settings/general"
    | "/_authenticated/_shell/_dashboard/settings/members"
    | "/_authenticated/_shell/_dashboard/clients/"
    | "/_authenticated/_shell/_dashboard/invoices/"
    | "/_authenticated/_shell/_dashboard/projects/"
    | "/_authenticated/_shell/_dashboard/settings/"
    | "/_authenticated/_shell/_dashboard/time/"
    | "/_authenticated/_shell/_dashboard/invoices/$invoiceId/print"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup/": {
      id: "/signup/"
      path: "/signup"
      fullPath: "/signup/"
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login/": {
      id: "/login/"
      path: "/login"
      fullPath: "/login/"
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/_shell": {
      id: "/_authenticated/_shell"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedShellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/onboarding/": {
      id: "/_authenticated/onboarding/"
      path: "/onboarding"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/new-org/": {
      id: "/_authenticated/new-org/"
      path: "/new-org"
      fullPath: "/new-org/"
      preLoaderRoute: typeof AuthenticatedNewOrgIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/_shell/superadmin": {
      id: "/_authenticated/_shell/superadmin"
      path: "/superadmin"
      fullPath: "/superadmin"
      preLoaderRoute: typeof AuthenticatedShellSuperadminRouteRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    "/_authenticated/_shell/_dashboard": {
      id: "/_authenticated/_shell/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    "/_authenticated/_shell/superadmin/": {
      id: "/_authenticated/_shell/superadmin/"
      path: "/"
      fullPath: "/superadmin/"
      preLoaderRoute: typeof AuthenticatedShellSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedShellSuperadminRouteRoute
    }
    "/_authenticated/_shell/account/": {
      id: "/_authenticated/_shell/account/"
      path: "/account"
      fullPath: "/account/"
      preLoaderRoute: typeof AuthenticatedShellAccountIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    "/_authenticated/_shell/_dashboard/": {
      id: "/_authenticated/_shell/_dashboard/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedShellDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/superadmin/organizations": {
      id: "/_authenticated/_shell/superadmin/organizations"
      path: "/organizations"
      fullPath: "/superadmin/organizations"
      preLoaderRoute: typeof AuthenticatedShellSuperadminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedShellSuperadminRouteRoute
    }
    "/_authenticated/_shell/_dashboard/settings": {
      id: "/_authenticated/_shell/_dashboard/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthenticatedShellDashboardSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/time/": {
      id: "/_authenticated/_shell/_dashboard/time/"
      path: "/time"
      fullPath: "/time/"
      preLoaderRoute: typeof AuthenticatedShellDashboardTimeIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/settings/": {
      id: "/_authenticated/_shell/_dashboard/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof AuthenticatedShellDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardSettingsRouteRoute
    }
    "/_authenticated/_shell/_dashboard/projects/": {
      id: "/_authenticated/_shell/_dashboard/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof AuthenticatedShellDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/invoices/": {
      id: "/_authenticated/_shell/_dashboard/invoices/"
      path: "/invoices"
      fullPath: "/invoices/"
      preLoaderRoute: typeof AuthenticatedShellDashboardInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/clients/": {
      id: "/_authenticated/_shell/_dashboard/clients/"
      path: "/clients"
      fullPath: "/clients/"
      preLoaderRoute: typeof AuthenticatedShellDashboardClientsIndexRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/settings/members": {
      id: "/_authenticated/_shell/_dashboard/settings/members"
      path: "/members"
      fullPath: "/settings/members"
      preLoaderRoute: typeof AuthenticatedShellDashboardSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedShellDashboardSettingsRouteRoute
    }
    "/_authenticated/_shell/_dashboard/settings/general": {
      id: "/_authenticated/_shell/_dashboard/settings/general"
      path: "/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof AuthenticatedShellDashboardSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedShellDashboardSettingsRouteRoute
    }
    "/_authenticated/_shell/_dashboard/settings/api-keys": {
      id: "/_authenticated/_shell/_dashboard/settings/api-keys"
      path: "/api-keys"
      fullPath: "/settings/api-keys"
      preLoaderRoute: typeof AuthenticatedShellDashboardSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedShellDashboardSettingsRouteRoute
    }
    "/_authenticated/_shell/_dashboard/projects/$projectSlug": {
      id: "/_authenticated/_shell/_dashboard/projects/$projectSlug"
      path: "/projects/$projectSlug"
      fullPath: "/projects/$projectSlug"
      preLoaderRoute: typeof AuthenticatedShellDashboardProjectsProjectSlugRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/invoices/new": {
      id: "/_authenticated/_shell/_dashboard/invoices/new"
      path: "/invoices/new"
      fullPath: "/invoices/new"
      preLoaderRoute: typeof AuthenticatedShellDashboardInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/invoices/$invoiceId": {
      id: "/_authenticated/_shell/_dashboard/invoices/$invoiceId"
      path: "/invoices/$invoiceId"
      fullPath: "/invoices/$invoiceId"
      preLoaderRoute: typeof AuthenticatedShellDashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/clients/$clientId": {
      id: "/_authenticated/_shell/_dashboard/clients/$clientId"
      path: "/clients/$clientId"
      fullPath: "/clients/$clientId"
      preLoaderRoute: typeof AuthenticatedShellDashboardClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedShellDashboardRouteRoute
    }
    "/_authenticated/_shell/_dashboard/invoices/$invoiceId/print": {
      id: "/_authenticated/_shell/_dashboard/invoices/$invoiceId/print"
      path: "/print"
      fullPath: "/invoices/$invoiceId/print"
      preLoaderRoute: typeof AuthenticatedShellDashboardInvoicesInvoiceIdPrintRouteImport
      parentRoute: typeof AuthenticatedShellDashboardInvoicesInvoiceIdRoute
    }
  }
}

interface AuthenticatedShellDashboardSettingsRouteRouteChildren {
  AuthenticatedShellDashboardSettingsApiKeysRoute: typeof AuthenticatedShellDashboardSettingsApiKeysRoute
  AuthenticatedShellDashboardSettingsGeneralRoute: typeof AuthenticatedShellDashboardSettingsGeneralRoute
  AuthenticatedShellDashboardSettingsMembersRoute: typeof AuthenticatedShellDashboardSettingsMembersRoute
  AuthenticatedShellDashboardSettingsIndexRoute: typeof AuthenticatedShellDashboardSettingsIndexRoute
}

const AuthenticatedShellDashboardSettingsRouteRouteChildren: AuthenticatedShellDashboardSettingsRouteRouteChildren =
  {
    AuthenticatedShellDashboardSettingsApiKeysRoute:
      AuthenticatedShellDashboardSettingsApiKeysRoute,
    AuthenticatedShellDashboardSettingsGeneralRoute:
      AuthenticatedShellDashboardSettingsGeneralRoute,
    AuthenticatedShellDashboardSettingsMembersRoute:
      AuthenticatedShellDashboardSettingsMembersRoute,
    AuthenticatedShellDashboardSettingsIndexRoute:
      AuthenticatedShellDashboardSettingsIndexRoute,
  }

const AuthenticatedShellDashboardSettingsRouteRouteWithChildren =
  AuthenticatedShellDashboardSettingsRouteRoute._addFileChildren(
    AuthenticatedShellDashboardSettingsRouteRouteChildren,
  )

interface AuthenticatedShellDashboardInvoicesInvoiceIdRouteChildren {
  AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute: typeof AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute
}

const AuthenticatedShellDashboardInvoicesInvoiceIdRouteChildren: AuthenticatedShellDashboardInvoicesInvoiceIdRouteChildren =
  {
    AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute:
      AuthenticatedShellDashboardInvoicesInvoiceIdPrintRoute,
  }

const AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren =
  AuthenticatedShellDashboardInvoicesInvoiceIdRoute._addFileChildren(
    AuthenticatedShellDashboardInvoicesInvoiceIdRouteChildren,
  )

interface AuthenticatedShellDashboardRouteRouteChildren {
  AuthenticatedShellDashboardSettingsRouteRoute: typeof AuthenticatedShellDashboardSettingsRouteRouteWithChildren
  AuthenticatedShellDashboardIndexRoute: typeof AuthenticatedShellDashboardIndexRoute
  AuthenticatedShellDashboardClientsClientIdRoute: typeof AuthenticatedShellDashboardClientsClientIdRoute
  AuthenticatedShellDashboardInvoicesInvoiceIdRoute: typeof AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren
  AuthenticatedShellDashboardInvoicesNewRoute: typeof AuthenticatedShellDashboardInvoicesNewRoute
  AuthenticatedShellDashboardProjectsProjectSlugRoute: typeof AuthenticatedShellDashboardProjectsProjectSlugRoute
  AuthenticatedShellDashboardClientsIndexRoute: typeof AuthenticatedShellDashboardClientsIndexRoute
  AuthenticatedShellDashboardInvoicesIndexRoute: typeof AuthenticatedShellDashboardInvoicesIndexRoute
  AuthenticatedShellDashboardProjectsIndexRoute: typeof AuthenticatedShellDashboardProjectsIndexRoute
  AuthenticatedShellDashboardTimeIndexRoute: typeof AuthenticatedShellDashboardTimeIndexRoute
}

const AuthenticatedShellDashboardRouteRouteChildren: AuthenticatedShellDashboardRouteRouteChildren =
  {
    AuthenticatedShellDashboardSettingsRouteRoute:
      AuthenticatedShellDashboardSettingsRouteRouteWithChildren,
    AuthenticatedShellDashboardIndexRoute:
      AuthenticatedShellDashboardIndexRoute,
    AuthenticatedShellDashboardClientsClientIdRoute:
      AuthenticatedShellDashboardClientsClientIdRoute,
    AuthenticatedShellDashboardInvoicesInvoiceIdRoute:
      AuthenticatedShellDashboardInvoicesInvoiceIdRouteWithChildren,
    AuthenticatedShellDashboardInvoicesNewRoute:
      AuthenticatedShellDashboardInvoicesNewRoute,
    AuthenticatedShellDashboardProjectsProjectSlugRoute:
      AuthenticatedShellDashboardProjectsProjectSlugRoute,
    AuthenticatedShellDashboardClientsIndexRoute:
      AuthenticatedShellDashboardClientsIndexRoute,
    AuthenticatedShellDashboardInvoicesIndexRoute:
      AuthenticatedShellDashboardInvoicesIndexRoute,
    AuthenticatedShellDashboardProjectsIndexRoute:
      AuthenticatedShellDashboardProjectsIndexRoute,
    AuthenticatedShellDashboardTimeIndexRoute:
      AuthenticatedShellDashboardTimeIndexRoute,
  }

const AuthenticatedShellDashboardRouteRouteWithChildren =
  AuthenticatedShellDashboardRouteRoute._addFileChildren(
    AuthenticatedShellDashboardRouteRouteChildren,
  )

interface AuthenticatedShellSuperadminRouteRouteChildren {
  AuthenticatedShellSuperadminOrganizationsRoute: typeof AuthenticatedShellSuperadminOrganizationsRoute
  AuthenticatedShellSuperadminIndexRoute: typeof AuthenticatedShellSuperadminIndexRoute
}

const AuthenticatedShellSuperadminRouteRouteChildren: AuthenticatedShellSuperadminRouteRouteChildren =
  {
    AuthenticatedShellSuperadminOrganizationsRoute:
      AuthenticatedShellSuperadminOrganizationsRoute,
    AuthenticatedShellSuperadminIndexRoute:
      AuthenticatedShellSuperadminIndexRoute,
  }

const AuthenticatedShellSuperadminRouteRouteWithChildren =
  AuthenticatedShellSuperadminRouteRoute._addFileChildren(
    AuthenticatedShellSuperadminRouteRouteChildren,
  )

interface AuthenticatedShellRouteRouteChildren {
  AuthenticatedShellDashboardRouteRoute: typeof AuthenticatedShellDashboardRouteRouteWithChildren
  AuthenticatedShellSuperadminRouteRoute: typeof AuthenticatedShellSuperadminRouteRouteWithChildren
  AuthenticatedShellAccountIndexRoute: typeof AuthenticatedShellAccountIndexRoute
}

const AuthenticatedShellRouteRouteChildren: AuthenticatedShellRouteRouteChildren =
  {
    AuthenticatedShellDashboardRouteRoute:
      AuthenticatedShellDashboardRouteRouteWithChildren,
    AuthenticatedShellSuperadminRouteRoute:
      AuthenticatedShellSuperadminRouteRouteWithChildren,
    AuthenticatedShellAccountIndexRoute: AuthenticatedShellAccountIndexRoute,
  }

const AuthenticatedShellRouteRouteWithChildren =
  AuthenticatedShellRouteRoute._addFileChildren(
    AuthenticatedShellRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRouteRoute: typeof AuthenticatedShellRouteRouteWithChildren
  AuthenticatedNewOrgIndexRoute: typeof AuthenticatedNewOrgIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRouteRoute: AuthenticatedShellRouteRouteWithChildren,
  AuthenticatedNewOrgIndexRoute: AuthenticatedNewOrgIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
