name: Checks for @repo/tsconfig
description: Run static checks.
runs:
  using: composite
  steps:
    - name: Static checks
      shell: bash
      working-directory: config/tsconfig
      run: pnpm exec vp check --no-error-on-unmatched-pattern .
