name: Checks for @repo/website
description: Run static checks.
runs:
  using: composite
  steps:
    - name: Static checks
      shell: bash
      working-directory: apps/website
      run: pnpm exec vp check --no-error-on-unmatched-pattern .
